src/Entity/Cours.php
<?php

namespace App\Entity;

use Assert\Callback;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CoursRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

#[ORM\Entity(repositoryClass: CoursRepository::class)]
class Cours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $max_eleves = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure_debut = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure_fin = null;

    #[ORM\Column(length: 20)]
    private ?string $date_hebdomadaire = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    

    #[ORM\OneToMany(mappedBy: 'cours', targetEntity: Inscrit::class)]
    private Collection $inscrits;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $utilisateur = null;

    #[ORM\OneToMany(mappedBy: 'cours_id', targetEntity: Seances::class)]
    private Collection $seances;

    public function __construct()
    {
        $this->inscrits = new ArrayCollection();
        $this->seances = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMaxEleves(): ?float
    {
        return $this->max_eleves;
    }

    public function setMaxEleves(float $max_eleves): self
    {
        $this->max_eleves = $max_eleves;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getHeureDebut(): ?\DateTimeInterface
    {
        return $this->heure_debut;
    }

    public function setHeureDebut(\DateTimeInterface $heure_debut): self
    {
        $this->heure_debut = $heure_debut;

        return $this;
    }

    public function getHeureFin(): ?\DateTimeInterface
    {
        return $this->heure_fin;
    }

    public function setHeureFin(\DateTimeInterface $heure_fin): self
    {
        $this->heure_fin = $heure_fin;

        return $this;
    }

    public function getDateHebdomadaire(): ?string
    {
        return $this->date_hebdomadaire;
    }

    public function setDateHebdomadaire(string $date_hebdomadaire): self
    {
        $this->date_hebdomadaire = $date_hebdomadaire;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection<int, Presence>
     */
    

    /**
     * @return Collection<int, Inscrit>
     */
    public function getInscrits(): Collection
    {
        return $this->inscrits;
    }

    public function addInscrit(Inscrit $inscrit): self
    {
        if (!$this->inscrits->contains($inscrit)) {
            $this->inscrits->add($inscrit);
            $inscrit->setCours($this);
        }

        return $this;
    }

    public function removeInscrit(Inscrit $inscrit): self
    {
        if ($this->inscrits->removeElement($inscrit)) {
            // set the owning side to null (unless already changed)
            if ($inscrit->getCours() === $this) {
                $inscrit->setCours(null);
            }
        }

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }
    public function getUtilisateurNom(): string
{
    return $this->utilisateur ? $this->utilisateur->getNomUtilisateur() : '';
}

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }


    /**
 * @param array $seances
 */
public function setSeances(array $seances): void
{
    $this->seances = new ArrayCollection($seances);
    foreach ($seances as $seance) {
        $seance->setCoursId($this);
    }
}

    /**
     * @return Collection<int, Seances>
     */
    public function getSeances(): Collection
    {
        return $this->seances;
    }

    public function addSeance(Seances $seance): self
    {
        if (!$this->seances->contains($seance)) {
            $this->seances->add($seance);
            $seance->setCoursId($this);
        }

        return $this;
    }

    public function removeSeance(Seances $seance): self
    {
        if ($this->seances->removeElement($seance)) {
            // set the owning side to null (unless already changed)
            if ($seance->getCoursId() === $this) {
                $seance->setCoursId(null);
            }
        }

        return $this;
    }
}

src/Entity/Presence.php
<?php

namespace App\Entity;

use App\Repository\PresenceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PresenceRepository::class)]
class Presence
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    

    #[ORM\Column]
    private ?int $validation_presence = null;

    #[ORM\ManyToOne(inversedBy: 'presences')]
    private ?Eleve $eleve = null;
   
    #[ORM\ManyToOne(inversedBy: 'presences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Seances $seances = null;

    public function getId(): ?int
    {
        return $this->id;
    }
   
    public function getValidationPresence(): ?int
    {
        return $this->validation_presence;
    }

    public function setValidationPresence(int $validation_presence): self
    {
        $this->validation_presence = $validation_presence;

        return $this;
    }

    public function getEleve(): ?Eleve
    {
        return $this->eleve;
    }

    public function setEleve(?Eleve $eleve): self
    {
        $this->eleve = $eleve;

        return $this;
    }
   
    public function getSeances(): ?Seances
    {
        return $this->seances;
    }

    public function setSeances(?Seances $seances): self
    {
        $this->seances = $seances;

        return $this;
    }

    //fonctions pour afficher les noms et prénoms des élèves inscrit aux cours sur les pages twig 
    public function getCoursNomEleve(): string
    {
    return $this->eleve ? $this->eleve->getNomEleve() : '';
    }

    public function getCoursPrenomEleve(): string
    {
    return $this->eleve ? $this->eleve->getPrenomEleve() : '';
    } 
}

src/Form/PresenceType.php
<?php

namespace App\Form;

use App\Entity\Eleve;
use App\Entity\Seances;
use App\Entity\Presence;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PresenceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_cours')
            ->add('validation_presence')
            ->add('eleve', EntityType::class, [
                'class' => Eleve::class,
                // On utilise le choice label getNomComplet() qui a été créer directement dans l'entité Eleve
                'choice_label' => 'nom_complet',
            ])
            ->add('seances', EntityType::class, [
                'class' => Seances::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Presence::class,
        ]);
    }
}

src/Controller/PresenceController.php
<?php

namespace App\Controller;

use App\Entity\Presence;
use App\Form\PresenceType;
use App\Repository\CoursRepository;
use App\Repository\PresenceRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/presence')]
#[IsGranted('ROLE_USER')]
class PresenceController extends AbstractController
{
    /**
     * Fonction pour afficher la liste des cours
     *
     * @param CoursRepository $coursRepository
     * @return Response
     */
    #[Route('/', name: 'app_presence_index', methods: ['GET'])]
    public function index(CoursRepository $coursRepository): Response
    {
        return $this->render('presence/listeCours.html.twig', [
            'cours' => $coursRepository->findAll(),
        ]);
    }
/**
     * fonction pour afficher la liste des inscrits à un cours particulier
     *
     * @param PresenceRepository $presenceRepository
     * @return Response
     */
    
    #[Route('/list/{id}', name: 'app_presence_list', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function indexPresence(PresenceRepository $presenceRepository): Response
    {
        return $this->render('presence/index.html.twig', [
            'presences' => $presenceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_presence_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PresenceRepository $presenceRepository): Response
    {
        $presence = new Presence();
        $form = $this->createForm(PresenceType::class, $presence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $presenceRepository->save($presence, true);

            return $this->redirectToRoute('app_presence_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('presence/new.html.twig', [
            'presence' => $presence,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_presence_show', methods: ['GET'])]
    public function show(Presence $presence): Response
    {
        return $this->render('presence/show.html.twig', [
            'presence' => $presence,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_presence_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Presence $presence, PresenceRepository $presenceRepository): Response
    {
        $form = $this->createForm(PresenceType::class, $presence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $presenceRepository->save($presence, true);

            return $this->redirectToRoute('app_presence_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('presence/edit.html.twig', [
            'presence' => $presence,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_presence_delete', methods: ['POST'])]
    public function delete(Request $request, Presence $presence, PresenceRepository $presenceRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$presence->getId(), $request->request->get('_token'))) {
            $presenceRepository->remove($presence, true);
        }

        return $this->redirectToRoute('app_presence_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/presence/_delete_form.html.twig
<form method="post" action="{{ path('app_presence_delete', {'id': presence.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ presence.id) }}">
    <button class="btn">Delete</button>
</form>

templates/presence/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/presence/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Presence{% endblock %}

{% block body %}
    <h1>Edit Presence</h1>

    {{ include('presence/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_presence_index') }}">back to list</a>

    {{ include('presence/_delete_form.html.twig') }}
{% endblock %}

templates/presence/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Presence index{% endblock %}

{% block body %}
    <h1>Presence index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Elève</th>                
                <th>Validation_presence</th>
                <th>seances_id</th>
                {# <th>actions</th> #}
            </tr>
        </thead>
        <tbody>
        {% for presence in presences %}
            <tr>
                <td>{{ presence.coursNomEleve }} {{ presence.coursPrenomEleve }}</td>                
                <td>{{ presence.validationPresence }}</td>
                <td>{{ presence.seances.id}}</td>
                {# <td>
                    <a href="{{ path('app_presence_show', {'id': presence.id}) }}">show</a>
                    <a href="{{ path('app_presence_edit', {'id': presence.id}) }}">edit</a>
                </td> #}
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Pas d'inscription à ce cours enregistré</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('app_presence_new') }}">Create new</a> #}
{% endblock %}

templates/presence/listeCours.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des cours (gestion des présences)
{% endblock %}

{% block body %}
	<div class="d-flex justify-content-center text-center row px-5 mx-1">
		<h1 class="mt-3">Liste des Cours</h1>
		<div class="p-5">
			<table class="table table-striped table-dark" id='dataTable'>
				<thead>
					<tr>
						{# <th class="bg-primary">Id</th> #}
						<th class="bg-primary">Libelle</th>
						<th class="bg-primary">Nombre max d'élèves</th>
						<th class="bg-primary">Description</th>						
						<th class="bg-primary">Heure du début</th>
						<th class="bg-primary">Heure de fin</th>
						<th class="bg-primary">Date hebdomadaire</th>
						<th class="bg-primary">date 1e session</th>
						<th class="bg-primary">date dernière session</th>
						<th class="bg-primary">professeur</th>
						<th class="bg-primary">Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for cour in cours %}

						<tr>
							{# <td>{{ cour.id }}</td> #}
							<td>{{ cour.libelle }}</td>
							<td>{{ cour.maxEleves }}</td>
							<td>{{ cour.description }}</td>				
				
							<td>{{ cour.heureDebut ? cour.heureDebut|date('H:i') : '' }}</td>
							<td>{{ cour.heureFin ? cour.heureFin|date('H:i') : '' }}</td>
							<td>{{ cour.dateHebdomadaire }}</td>
							<td>{{ cour.dateDebut ? cour.dateDebut|date('Y-m-d') : '' }}</td>
							<td>{{ cour.dateFin ? cour.dateFin|date('Y-m-d') : '' }}</td>
							<td>{{ cour.utilisateurNom }}</td>
							<td style="width: 13%;">
								<a class="btn btn-sm btn-outline-primary m-1" href="{{ path('app_presence_list', {'id': cour.id}) }}">Voir</a>
								{# <a class="btn btn-sm btn-outline-primary m-1" href="{{ path('app_inscrit_new', {'id': cour.id}) }}">Inscrire</a> #}
							</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="10">Pas de cours enregistrés</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>


	{# <div class="w-25 order-2"></div>
	<div class="w-25 order-1"></div> #}
</div>{% endblock %}

templates/presence/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Presence{% endblock %}

{% block body %}
    <h1>Create new Presence</h1>

    {{ include('presence/_form.html.twig') }}

    <a href="{{ path('app_presence_index') }}">back to list</a>
{% endblock %}

templates/presence/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Presence{% endblock %}

{% block body %}
    <h1>Presence</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ presence.id }}</td>
            </tr>
            <tr>
                <th>Date_cours</th>
                <td>{{ presence.dateCours ? presence.dateCours|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Validation_presence</th>
                <td>{{ presence.validationPresence }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_presence_index') }}">back to list</a>

    <a href="{{ path('app_presence_edit', {'id': presence.id}) }}">edit</a>

    {{ include('presence/_delete_form.html.twig') }}
{% endblock %}