src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use LogicException;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface, TwoFactorInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_utilisateur = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom_utilisateur = null;

    #[ORM\Column]
    private ?string $telephone_utilisateur = null;

    #[ORM\Column(length: 20)]
    private ?string $sexe_utilisateur = null;

    
    
     #[ORM\Column(type: 'string', nullable: true)]    
    private ?string $authCode;
    

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Cours::class)]
    private Collection $cours;

    #[ORM\Column(length: 255)]
    private ?string $color = null;
    

    public function __construct()
    {
        $this->cours = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNomUtilisateur(): ?string
    {
        return $this->nom_utilisateur;
    }

    public function setNomUtilisateur(string $nom_utilisateur): self
    {
        $this->nom_utilisateur = $nom_utilisateur;

        return $this;
    }

    public function getPrenomUtilisateur(): ?string
    {
        return $this->prenom_utilisateur;
    }

    public function setPrenomUtilisateur(string $prenom_utilisateur): self
    {
        $this->prenom_utilisateur = $prenom_utilisateur;

        return $this;
    }

    public function getTelephoneUtilisateur(): ?float
    {
        return $this->telephone_utilisateur;
    }

    public function setTelephoneUtilisateur(float $telephone_utilisateur): self
    {
        $this->telephone_utilisateur = $telephone_utilisateur;

        return $this;
    }

    public function getSexeUtilisateur(): ?string
    {
        return $this->sexe_utilisateur;
    }

    public function setSexeUtilisateur(string $sexe_utilisateur): self
    {
        $this->sexe_utilisateur = $sexe_utilisateur;

        return $this;
    }

    /**
     * @return Collection<int, Cours>
     */
    public function getCours(): Collection
    {
        return $this->cours;
    }

    public function addCour(Cours $cour): self
    {
        if (!$this->cours->contains($cour)) {
            $this->cours->add($cour);
            $cour->setUtilisateur($this);
        }

        return $this;
    }

    public function removeCour(Cours $cour): self
    {
        if ($this->cours->removeElement($cour)) {
            // set the owning side to null (unless already changed)
            if ($cour->getUtilisateur() === $this) {
                $cour->setUtilisateur(null);
            }
        }

        return $this;
    }

    public function isEmailAuthEnabled(): bool
    {
        return true; // This can be a persisted field to switch email code authentication on/off
    }

    public function getEmailAuthRecipient(): string
    {
        return $this->email;
    }

    public function getEmailAuthCode(): string
    {
        if (null === $this->authCode) {
            throw new LogicException('The email authentication code was not set');
        }

        return $this->authCode;
    }

    public function setEmailAuthCode(string $authCode): void
    {
        $this->authCode = $authCode;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }

}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateur;
use App\Form\Utilisateur1Type;
use App\Repository\UtilisateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/profile')]
class ProfileController extends AbstractController
{
   

    #[Route('/', name: 'app_profile_show', methods: ['GET'])]
    public function show(): Response
    {
        $utilisateur = $this->getUser();
        return $this->render('profile/show.html.twig', [
            'utilisateur' => $utilisateur,
        ]);
    }

    #[Route('/edit', name: 'app_profile_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, UtilisateurRepository $utilisateurRepository): Response
    {
        $utilisateur = $this->getUser();
        $form = $this->createForm(Utilisateur1Type::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $utilisateurRepository->save($utilisateur, true);

            return $this->redirectToRoute('app_profile_show', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('profile/edit.html.twig', [
            'utilisateur' => $utilisateur,
            'editprofilform' => $form,
        ]);
    }
}

templates/profile/_form.html.twig
{{ form_start(editprofilform) }}
    {{ form_widget(editprofilform) }}
    <button class="btn btn-primary mt-2">{{ button_label|default('Save') }}</button>
{{ form_end(editprofilform) }}

templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Utilisateur{% endblock %}

{% block body %}
    <h1>Modifier vos information</h1>

    {{ form_start(editprofilform) }}


	{# premiere ligne #}
	<div class="d-flex justify-content-around m-5 mt-5">
		<div class="w-25 card1 m-2 p-2">{{ form_row(editprofilform.nom_utilisateur) }}</div>
		<div class="w-25 card1 m-2 p-2">{{ form_row(editprofilform.prenom_utilisateur) }}</div>
		<div class="w-25 card1 m-2 p-2">{{ form_row(editprofilform.email) }}</div>
	</div>

	{# deuxieme ligne #}
	<div class="d-flex justify-content-around m-5 mt-5">
		<div class="w-25 card1 m-2 p-2">{{ form_row(editprofilform.password) }}</div>
		<div class="w-25 card1 m-2 p-2">{{ form_row(editprofilform.sexe_utilisateur)}} </div>
		<div class="w-25 card1 m-2 p-2">{{ form_row(editprofilform.telephone_utilisateur) }}</div>
	</div>

	{# ligne avec boutons retour valider supprimer #}
	<div class="d-flex justify-content-around">
		<div class="w-25 d-flex justify-content-center order-3">{{ include('profile/_form.html.twig', { button_label: 'Modifier' }) }}</div>
		<div class="w-25 d-flex justify-content-center order-2"></div>
		<div class="w-25 d-flex justify-content-center order-1">
			<a class="btn btn-outline-primary mt-2" href="{{ path('app_profile_show') }}">Retour au profil</a>
		</div>
	</div>
	</div>
	{{ form_end(editprofilform) }}

{% endblock %}

templates/profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur
{% endblock %}

{% block body %}


	<div class="d-flex justify-content-center text-center row px-5  mx-1">
		<h1 class="text-center my-5">Bonjour
			{{ utilisateur.prenomUtilisateur }}
		</h1>

		<div class="d-flex justify-content-center">
			<table class="table table-dark table-striped">
				<tbody>

					<tr>
						<th>Email</th>
						<td>{{ utilisateur.email }}</td>
					</tr>

					<tr>
						<th>Nom_utilisateur</th>
						<td>{{ utilisateur.nomUtilisateur }}</td>
					</tr>
					<tr>
						<th>Prenom_utilisateur</th>
						<td>{{ utilisateur.prenomUtilisateur }}</td>
					</tr>
					<tr>
						<th>Telephone_utilisateur</th>
						<td>{{ utilisateur.telephoneUtilisateur }}</td>
					</tr>
					<tr>
						<th>Sexe_utilisateur</th>
						<td>{{ utilisateur.sexeUtilisateur }}</td>
					</tr>

				</tbody>
			</table>
		</div>
	</div>
	<div class="d-flex justify-content-around">
		<div class="w-25 d-flex justify-content-center order-3 mt-3">
			<a class="btn btn-primary mt-2" href="{{ path('app_profile_edit') }}">Modifier</a>
		</div>
		<div class="w-25 order-2"></div>
		<div class="w-25 order-1"></div>
	</div>
{% endblock %}