src/Entity/Cours.php
<?php

namespace App\Entity;

use Assert\Callback;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CoursRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

#[ORM\Entity(repositoryClass: CoursRepository::class)]
class Cours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $max_eleves = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure_debut = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure_fin = null;

    #[ORM\Column(length: 20)]
    private ?string $date_hebdomadaire = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    

    #[ORM\OneToMany(mappedBy: 'cours', targetEntity: Inscrit::class)]
    private Collection $inscrits;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $utilisateur = null;

    #[ORM\OneToMany(mappedBy: 'cours_id', targetEntity: Seances::class)]
    private Collection $seances;

    public function __construct()
    {
        $this->inscrits = new ArrayCollection();
        $this->seances = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMaxEleves(): ?float
    {
        return $this->max_eleves;
    }

    public function setMaxEleves(float $max_eleves): self
    {
        $this->max_eleves = $max_eleves;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getHeureDebut(): ?\DateTimeInterface
    {
        return $this->heure_debut;
    }

    public function setHeureDebut(\DateTimeInterface $heure_debut): self
    {
        $this->heure_debut = $heure_debut;

        return $this;
    }

    public function getHeureFin(): ?\DateTimeInterface
    {
        return $this->heure_fin;
    }

    public function setHeureFin(\DateTimeInterface $heure_fin): self
    {
        $this->heure_fin = $heure_fin;

        return $this;
    }

    public function getDateHebdomadaire(): ?string
    {
        return $this->date_hebdomadaire;
    }

    public function setDateHebdomadaire(string $date_hebdomadaire): self
    {
        $this->date_hebdomadaire = $date_hebdomadaire;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection<int, Presence>
     */
    

    /**
     * @return Collection<int, Inscrit>
     */
    public function getInscrits(): Collection
    {
        return $this->inscrits;
    }

    public function addInscrit(Inscrit $inscrit): self
    {
        if (!$this->inscrits->contains($inscrit)) {
            $this->inscrits->add($inscrit);
            $inscrit->setCours($this);
        }

        return $this;
    }

    public function removeInscrit(Inscrit $inscrit): self
    {
        if ($this->inscrits->removeElement($inscrit)) {
            // set the owning side to null (unless already changed)
            if ($inscrit->getCours() === $this) {
                $inscrit->setCours(null);
            }
        }

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }
    public function getUtilisateurNom(): string
{
    return $this->utilisateur ? $this->utilisateur->getNomUtilisateur() : '';
}

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }


    /**
 * @param array $seances
 */
public function setSeances(array $seances): void
{
    $this->seances = new ArrayCollection($seances);
    foreach ($seances as $seance) {
        $seance->setCoursId($this);
    }
}

    /**
     * @return Collection<int, Seances>
     */
    public function getSeances(): Collection
    {
        return $this->seances;
    }

    public function addSeance(Seances $seance): self
    {
        if (!$this->seances->contains($seance)) {
            $this->seances->add($seance);
            $seance->setCoursId($this);
        }

        return $this;
    }

    public function removeSeance(Seances $seance): self
    {
        if ($this->seances->removeElement($seance)) {
            // set the owning side to null (unless already changed)
            if ($seance->getCoursId() === $this) {
                $seance->setCoursId(null);
            }
        }

        return $this;
    }
}

src/Entity/Inscrit.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\InscritRepository;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: InscritRepository::class)]
#[UniqueEntity(fields: ['eleve', 'cours'], message: 'Cet élève est déjà inscrit à ce cours')]
class Inscrit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'inscrits')]
    private ?Eleve $eleve = null;

    #[ORM\ManyToOne(inversedBy: 'inscrits')]
    private ?Cours $cours = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEleve(): ?Eleve
    {
        return $this->eleve;
    }

    public function setEleve(?Eleve $eleve): self
    {
        $this->eleve = $eleve;

        return $this;
    }

    public function getCours(): ?Cours
    {
        return $this->cours;
    }

    

    public function setCours(?Cours $cours): self
    {
        $this->cours = $cours;

        return $this;
    }

    //fonction pour afficher le libelle des cours sur les pages twig    
    public function getCoursLibelle(): string
    {
    return $this->cours ? $this->cours->getLibelle() : '';
    }

    //fonctions pour afficher le nombre max d'élèves d'un cours sur les pages twig 
    public function getCoursMaxEleves(): string
    {
    return $this->cours ? $this->cours->getMaxEleves() : '';
    }

    //fonctions pour afficher les noms et prénoms des élèves inscrit aux cours sur les pages twig 
    public function getCoursNomEleve(): string
    {
    return $this->eleve ? $this->eleve->getNomEleve() : '';
    }

    public function getCoursPrenomEleve(): string
    {
    return $this->eleve ? $this->eleve->getPrenomEleve() : '';
    }    
 }   

src/Controller/InscritController.php
<?php

namespace App\Controller;

use App\Entity\Cours;
use App\Entity\Inscrit;
use App\Entity\Presence;
use App\Form\InscritType;
use App\Repository\CoursRepository;
use App\Repository\InscritRepository;
use App\Repository\PresenceRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/inscrit')]
#[IsGranted('ROLE_USER')]
class InscritController extends AbstractController
{
    /**
     * Fonction pour afficher la liste des cours
     *
     * @param CoursRepository $coursRepository
     * @return Response
     */
    #[Route('/', name: 'app_inscrit_index', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function index(CoursRepository $coursRepository): Response
    {
        return $this->render('inscrit/listeCours.html.twig', [
            'cours' => $coursRepository->findAll(),           
        ]);
    }

    /**
     * fonction pour afficher la liste des inscrits à un cours particulier
     *
     * @param InscritRepository $inscritRepository
     * @return Response
     */
    
    #[Route('/list/{id}', name: 'app_inscrit_list', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function indexInscrit(InscritRepository $inscritRepository): Response
    {
        return $this->render('inscrit/index.html.twig', [
            'inscrits' => $inscritRepository->findAll(),
        ]);
    }

    /**
     * Fonction pour créer un inscrit mais en assignant par défaut l'id du cours présent dans l'url
     */
    #[Route('/new/{id}', name: 'app_inscrit_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function new(Request $request, InscritRepository $inscritRepository, int $id, EntityManagerInterface $entityManager): Response
    {    
        //l'entitée Manager va chercher l'id du Cours qui est présent dans l'url         
        $cours = $entityManager->getRepository(Cours::class)->find($id);
        
        // Compte le nombre le nombre d'objets inscrits qui sont associé à l'objet cours dont l'id est dans l'url (c'est à dire lnombre d'élèves inscrits à ce cours)
        $nbInscrits = $inscritRepository->count(['cours' => $cours]);
        
        //Compare le nombre max d'élèves du cours dont l'id est présente dans l'url avec le nb d'inscrits
        if ($nbInscrits >= $cours->getMaxEleves()) {
            $this->addFlash('error', 'Le cours est complet');            
            return $this->redirectToRoute('app_inscrit_list', ['id'=>$id]);
        }

        //On crée un nouvel objet inscrit et on lui assigne directement l'objet cours (que l'on a récuppéré précédemment avec l'id dans l'url)
        $inscrit = new Inscrit();
        $inscrit->setCours($cours);

        $form = $this->createForm(InscritType::class, $inscrit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $inscritRepository->save($inscrit, true);
            
            //partie pour générer la table des présences dès ques les élèves s'inscrivent

            //récuppération des données lors de la création de l'inscrit
            //Les élèves inscrits sont de base noté en absent pour chaque cours (ils doivent modifier leur statut à posteriori)            
            $validationPressence = 0;
            $eleve = $form->get('eleve')->getData();
            //Ici le controlleur récuppère une collection d'objets Seances associé à l'objet Cours
            $seances = $inscrit->getCours()->getSeances();

            //Création des objets Presences pour chaque Seances de la collection
            foreach ($seances as $seance) {
                $presence = new Presence();
                $presence->setValidationPresence($validationPressence);
                $presence->setEleve($eleve);
                $presence->setSeances($seance);

                // sauvegarde de l'objet Presence dans la base de données
                $entityManager->persist($presence);
            }               
            $entityManager->flush();

            //'id' permet de rediriger après l'inscription sur la page du cours sur lequel l'utilisateur était précédemment
            return $this->redirectToRoute('app_inscrit_list', ['id'=>$id], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('inscrit/new.html.twig', [
            'inscrit' => $inscrit,
            'form' => $form,           

        ]);
    }

    /**
     * Fonction pour afficher les détails d'un inscrit
     */
    #[Route('/{id}', name: 'app_inscrit_show', methods: ['GET'])]
    #[IsGranted('ROLE_USER')]
    public function show(Inscrit $inscrit): Response
    {
        return $this->render('inscrit/show.html.twig', [
            'inscrit' => $inscrit,
        ]);
    }

    /**
     * Fonction pour modifier un inscrit
     */
    #[Route('/{id}/edit', name: 'app_inscrit_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_USER')]
    public function edit(Request $request, Inscrit $inscrit, InscritRepository $inscritRepository, int $id, PresenceRepository $presenceRepository): Response
    {
        //On récuppère l'id de l'élève qui était inscrit pour le moment (avant l'update), cette varaible est utile pour la modification de la table Presence
        $eleveInscrit = $inscrit->getEleve()->getId();

        //création du formulaire
        $form = $this->createForm(InscritType::class, $inscrit);
        $form->handleRequest($request);
        

        if ($form->isSubmitted() && $form->isValid()) {
            $inscritRepository->save($inscrit, true);

            //partie pour modifié également l'élève dans la table Presence dont les cours sont associés

            //récuppération des données lors de la modification de l'inscrit
            $eleve = $form->get('eleve')->getData();            
            $seances = $inscrit->getCours()->getSeances();
            

            //On parcours les séances associés à ce cour            
            foreach ($seances as $seance) {
                $presences = $seance->getPresences();
                //on parcours les présences associés à ces séances
                foreach ($presences as $presence) {
                    //On identifie les élèves inscrit aux séances
                    $elevePresence = $presence->getEleve()->getId();
                    
                    //Si il s'agit d'une séance dont l'élève inscrit est celui qu'on souhaite modifier, alors l'update se réalise
                    if ($elevePresence == $eleveInscrit) {
                        $presence->setEleve($eleve);
                        $presenceRepository->save($presence, true);
                    }
                }
            }            
            

            return $this->redirectToRoute('app_inscrit_edit', ['id'=>$id], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('inscrit/edit.html.twig', [
            'inscrit' => $inscrit,
            'form' => $form,
        ]);
    }

    /**
     * Fonction pour supprimer un inscrit
     */
    #[Route('/{id}', name: 'app_inscrit_delete', methods: ['POST'])]
    #[IsGranted('ROLE_USER')]
    public function delete(Request $request, Inscrit $inscrit, InscritRepository $inscritRepository, PresenceRepository $presenceRepository): Response
    {
        //On récuppère l'id de l'élève qui était inscrit, cette varaible est utile pour la modification de la table Presence
        $eleveInscrit = $inscrit->getEleve()->getId();

        if ($this->isCsrfTokenValid('delete'.$inscrit->getId(), $request->request->get('_token'))) {
            $inscritRepository->remove($inscrit, true);

            //partie pour supprimer également l'élève dans la table Presence dont les cours sont associés

            //récuppération des données lors de la suppresion de l'inscrit
            $seances = $inscrit->getCours()->getSeances();

            //On parcours les séances associés à ce cour
            foreach ($seances as $seance) {
                $presences = $seance->getPresences();
                //on parcours les présences associés à ces séances
                foreach ($presences as $presence) {
                    //On identifie les élèves inscrit aux séances
                    $elevePresence = $presence->getEleve()->getId();
                    
                    //Si il s'agit d'une séance ayant le même élève alors on supprime la séance
                    if ($elevePresence == $eleveInscrit) {                        
                        $presenceRepository->remove($presence, true);
                    }
                }
            }
            //Si problème rajouter ?
            // $entityManager->flush();

        }

        return $this->redirectToRoute('app_inscrit_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/inscrit/_delete_form.html.twig
<form method="post" action="{{ path('app_inscrit_delete', {'id': inscrit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ inscrit.id) }}">
    <button class="btn btn-warning mt-2">Supprimer</button>
</form>

templates/inscrit/_form.html.twig
{{ form_start(form) }}
    
    {{ form_widget(form) }}
    <div>
    <button class="btn btn-outline-primary mt-4">{{ button_label|default('Inscrire') }}</button>
    </div>
{{ form_end(form) }}

templates/inscrit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier l'élève inscrit
{% endblock %}

{% block body %}

	{# titre #}
	<div class="d-flex justify-content-center text-center row px-5 mx-1">
		<h1 class="mt-3">Modifier l'élève inscrit</h1>
	</div>

	{# formulaire #}
	<div class="mx-3">
		<p class="mx-2">Actuellement
			{{ inscrit.coursPrenomEleve }}
			{{ inscrit.coursNomEleve }}
		</p>
		<div class="d-flex mx-2">
			{{ include('inscrit/_form.html.twig', {'button_label': 'Modifier'}) }}
		</div>

		{# Bouton de retour #}
		<div class="mt-5 d-flex ">
			<a class="btn btn-primary mt-2 mx-2" href="{{ path('app_inscrit_index') }}">Retour à la liste des cours</a>

            {{ include('inscrit/_delete_form.html.twig') }}
		</div>

		
	</div>
{% endblock %}

templates/inscrit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des inscrits
{% endblock %}

{% block body %}
	<div class="d-flex justify-content-center text-center row px-5  mx-1">
		<h1 class="mt-3">Liste des inscrits</h1>
		<div class="p-5">


			<table class="table table-striped table-dark" id="dataTable">
				<thead>
					<tr>
						<th class="bg-primary">cours</th>
						<th class="bg-primary">Maximum d'élèves</th>
						<th class="bg-primary">Nom et prénom</th>
						<th class="bg-primary">actions</th>
					</tr>
				</thead>
				<tbody>
					{% for inscrit in inscrits %}
						{% if app.request.get('id') == inscrit.cours.id %}

							<tr>
								<td>
									{{ inscrit.coursLibelle }}
								</td>
								<td>
									{{ inscrit.coursMaxEleves }}
								</td>
								<td>
									{{ inscrit.coursNomEleve }}
									{{ inscrit.coursPrenomEleve }}
								</td>
								<td style="width: 25%;">
									<a class="btn btn-sm btn-outline-primary m-1" href="{{ path('app_inscrit_show', {'id': inscrit.id}) }}">Voir</a>
									<a class="btn btn-sm btn-outline-primary m-1" href="{{ path('app_inscrit_edit', {'id': inscrit.id}) }}">Modifier l'élève inscrit</a>
								</td>
							</tr>
						{% endif %}
					{% else %}
						<tr>
							<td colspan="2">pas de données</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

	{# Message d'alerte si il y a déjà trop de personnes inscrites au cours #}
	<div class="d-flex justify-content-around ">
		{% for label, messages in app.flashes %}
			{% for message in messages %}
				<div class="alert card text-white bg-danger mb-3 alert-{{ label }}" style="max-width: 20rem;">
					{{ message }}
				</div>
			{% endfor %}
		{% endfor %}
	</div>

	<div class="d-flex justify-content-around">
		<a class="btn btn-primary mt-2" href="{{ path('app_inscrit_index') }}">Retour à la liste des cours</a>
		<br>
		{# app.request.get('id') va chercher l'id du cours pour pouvoir inscire un élève directement sur le bon cours #}
		<a class="btn btn-primary mt-2" href="{{ path('app_inscrit_new', {'id': app.request.get('id')}) }}">Inscrire un élève</a>


	</div>
{% endblock %}

templates/inscrit/listeCours.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des cours (gestion des inscrits)
{% endblock %}

{% block body %}
	<div class="d-flex justify-content-center text-center row px-5 mx-1">
		<h1 class="mt-3">Liste des Cours</h1>
		<div class="p-5">
			<table class="table table-striped table-dark" id='dataTable'>
				<thead>
					<tr>
						{# <th class="bg-primary">Id</th> #}
						<th class="bg-primary">Libelle</th>
						<th class="bg-primary">Nombre max d'élèves</th>
						<th class="bg-primary">Description</th>						
						<th class="bg-primary">Heure du début</th>
						<th class="bg-primary">Heure de fin</th>
						<th class="bg-primary">Date hebdomadaire</th>
						<th class="bg-primary">date 1e session</th>
						<th class="bg-primary">date dernière session</th>
						<th class="bg-primary">professeur</th>
						<th class="bg-primary">Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for cour in cours %}

						<tr>
							{# <td>{{ cour.id }}</td> #}
							<td>{{ cour.libelle }}</td>
							<td>{{ cour.maxEleves }}</td>
							<td>{{ cour.description }}</td>				
				
							<td>{{ cour.heureDebut ? cour.heureDebut|date('H:i') : '' }}</td>
							<td>{{ cour.heureFin ? cour.heureFin|date('H:i') : '' }}</td>
							<td>{{ cour.dateHebdomadaire }}</td>
							<td>{{ cour.dateDebut ? cour.dateDebut|date('Y-m-d') : '' }}</td>
							<td>{{ cour.dateFin ? cour.dateFin|date('Y-m-d') : '' }}</td>
							<td>{{ cour.utilisateurNom }}</td>
							<td style="width: 13%;">
								<a class="btn btn-sm btn-outline-primary m-1" href="{{ path('app_inscrit_list', {'id': cour.id}) }}">Voir</a>
								<a class="btn btn-sm btn-outline-primary m-1" href="{{ path('app_inscrit_new', {'id': cour.id}) }}">Inscrire</a>
							</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="10">Pas de cours enregistrés</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>


	{# <div class="w-25 order-2"></div>
	<div class="w-25 order-1"></div> #}
</div>{% endblock %}

templates/inscrit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscrire un élève à un cours
{% endblock %}

{% block body %}
    {# titre #}
	<div class="d-flex justify-content-center text-center row px-5 mx-1">
		<h1 class="mt-3">Inscription à un cours</h1>
	</div>

    {# formulaire #}
	<div class="mx-3">
		<div class="d-flex ">
			{{ include('inscrit/_form.html.twig') }}
		</div>

        {# Bouton de retour #}
		<div class="mt-5">
			<a class="btn btn-primary mt-2" href="{{ path('app_inscrit_index') }}">Retour à la liste des cours</a>
		</div>
	</div>
{% endblock %}

templates/inscrit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscrit{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center text-center row px-5  mx-1">
    <h1 class="mt-3">Cours de {{ inscrit.coursLibelle }}</h1>
    <div class="p-5">
        <table class="table table-striped table-dark">
            <tbody>
                <tr>
                    <th class="w-50" style="padding-left: 150px;">Id</div></th>
                    <td class="w-50" style="padding-left: 150px;">{{ inscrit.id }}</td>
                </tr>
                <tr>
                    <th class="w-50" style="padding-left: 150px;">Libelle du cours</div></th>
                    <td class="w-50" style="padding-left: 150px;">{{ inscrit.coursLibelle }}</td>
                </tr>
                <tr>
                    <th class="w-50" style="padding-left: 150px;">Nom et prénom</div></th>
                    <td class="w-50" style="padding-left: 150px;"> {{ inscrit.coursNomEleve }} {{ inscrit.coursPrenomEleve }} </td>
                </tr>                
            </tbody>
        </table>
    </div>
    </div>
    <div class="d-flex justify-content-around">
        <div class="w-25 d-flex justify-content-center order-3">
            <a class="btn btn-primary mt-2" href="{{ path('app_inscrit_edit', {'id': inscrit.id}) }}">Modifier l'élève inscrit</a>
        </div>
    <div class="w-25 d-flex justify-content-center order-2">
        <a class="btn btn-outline-primary mt-2" href="{{ path('app_inscrit_index') }}">Retour à la liste des cours</a>
        </div>    
        
        <div class="w-25 d-flex justify-content-center order-2">
            {{ include('inscrit/_delete_form.html.twig') }}
        </div>
        </div>    
{% endblock %}